### ISSUE TITLE
Erreur lors de la compilation du client et de l'éditeur

### ISSUE THREAD

**Issue by Caranille** [Iberos/FRoG-Creator#10]
Bonjour,

Je viens de télécharger le git complet au format .zip, le problème vient du client qui m'affiche une erreur (Voir L'image ci-dessous

![erreur](https://cloud.githubusercontent.com/assets/923600/8872675/7c6b9542-31ff-11e5-9aad-4134914a0bda.PNG)

Même chose pour l'éditeur

![erreur2](https://cloud.githubusercontent.com/assets/923600/8872688/a1e13cb4-31ff-11e5-9c61-8b2d120ae94e.PNG)

**Comment by ClementDidier** [comment]
Le projet à été réalisé avec Visual Studio 2013. Il faut donc l'ouvrir de préférence avec cette version afin de ne pas modifier quelques configurations pour le gestionnaire de package NuGet.

**Comment by Caranille** [comment]
Oui mais Visual Studio 2013 tire sa révérance pour Visual Studio 2015, et pour vous aider sur le projet j'utilise Visual Studio 2015 de plus les futurs utilisateurs de frog n'auront pas visual studio 2013

**Comment by ClementDidier** [comment]
MSBuild 14.0 remplacé par Core.
