### ISSUE TITLE
Chargement des cartes de jeu

### ISSUE THREAD

**Issue by ClementDidier** [Iberos/FRoG-Creator#2]
Le chargement des cartes auprès du client correspond à la déserialisation des fichiers '.frog' dans le dossier Maps situé dans les ressources clientes.
Pour que cette déserialisation marche, il faut que la class GameMap dans l'éditeur ait les mêmes attributs et les mêmes parents (héritage, implémentations...). 

Question >> Sérialisation et désérialisation possible entre 2 projets différents ? (Client / Editeur)

L'architecture de l'éditeur au niveau du chargement et du dessin des GameMap est donc à modifier légèrement, afin de réduire le nombre de méthodes et de s'accorder à l'architecture cliente actuelle.

Le problème actuel : La map sérialisée auprès de l'éditeur ne veut pas se déserialiser auprès du client. (Assembly différentes). Et le Binder crée à cet effet ne fonctionne pas.

**Comment by ClementDidier** [comment]
Correction : Le Binder ne remplaçait pas correctement les espaces de noms.

**Comment by Iberos** [comment]
Il y avait une autre solution : dans les settings de l'éditeur on pouvait spécifier que les fichiers binaires ne soient pas signés. Cela les rend lisibles sur n'importe quel autre projet.

**Comment by ClementDidier** [comment]
Effectivement, mais le mieux est d'adapter plutôt que laisser libre a n'importe quelle solution. En tout cas c'est ce que j'en pense.
