### ISSUE TITLE
Exclure le dossier bin/ des commits

### ISSUE THREAD

**Issue by TeddyRilliot** [Iberos/FRoG-Creator#7]
Le suivi des fichiers binaires n'est pas recommandé, car ils changent à chaque test/compilation et alourdissent le projet.

Il est possible de laisser les dépendances (SFML), mais le mieux serait de complètement supprimer le dossier `bin/` et de l'ajouter au `.gitignore`.

Le travail est compliqué car il faut préserver les configs, les ressources graphiques, etc...

**Comment by ClementDidier** [comment]
J'ai commencé la partie de déserialisation des maps auprès du client. C'est pourquoi j'ai consciemment activer le suivi afin de permettre a l'équipe de continuer a debug tranquillement. Bien évidement, dès que je trouverais le temps de catch l'inexistence des fichiers auprès du client (code) je remettrai le bin\ en gitignore.
